apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: payment-service
          image: slopeoasisacr.azurecr.io/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          readinessProbe: #tuki
            httpGet:
              path: /healthpayment
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthpayment
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3 #tuki
          env:
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: payment-db-secret
                    key: PGUSER
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: payment-db-secret
                    key: PGPASSWORD
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: payment-db-secret
                    key: PGHOST
              - name: PGPORT
                valueFrom:
                  secretKeyRef:
                    name: payment-db-secret
                    key: PGPORT
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: payment-db-secret
                    key: PGDATABASE
              - name: COINGECKO_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: payment-service-secrets
                    key: COINGECKO_API_KEY
              - name: USER_SERVICE_BASE_URL
                value: http://user-service:8080
              - name: POST_SERVICE_BASE_URL
                value: http://post-service:8081
          envFrom:
            - configMapRef:
                name: payment-service-config
