apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
type: Opaque
data:
  PGHOST: dXNlcmRhdGFiYXNlLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  PGUSER: dXNlcmFkbWlu
  PGPORT: NTQzMg==
  PGDATABASE: cGF5bWVuZGI=
  PGPASSWORD: cGFzc3dvcmQyOTch